# Generated by Django 4.1.7 on 2023-04-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Destinacao",
            fields=[
                (
                    "id_destinacao",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Destinação",
                "verbose_name_plural": "Destinações",
                "db_table": "destinacao",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Fornecedor",
            fields=[
                (
                    "id_fornecedor",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("nome", models.CharField(max_length=50)),
                (
                    "id_destinacao",
                    models.ManyToManyField(
                        db_table="fornecedor_destinacao",
                        related_name="destinacao",
                        to="fornecedor.destinacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fornecedor",
                "verbose_name_plural": "Fornecedores",
                "db_table": "fornecedor",
                "ordering": ["nome"],
            },
        ),
    ]
