# Generated by Django 4.2.6 on 2023-10-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fornecedor", "0001_initial"),
        ("localidade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Agua",
            fields=[
                ("id_agua", models.AutoField(primary_key=True, serialize=False)),
                ("dt_agua", models.DateField()),
                (
                    "consumo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "id_fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fornecedor.fornecedor",
                    ),
                ),
                (
                    "id_localidade",
                    models.ForeignKey(
                        db_column="id_localidade",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="localidade.localidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumo de água",
                "verbose_name_plural": "Consumo de água",
                "db_table": "agua",
                "ordering": ["-id_agua"],
            },
        ),
    ]
