# Generated by Django 4.2.6 on 2023-10-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cluster",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=25)),
                ("estado", models.CharField(max_length=2)),
            ],
            options={
                "verbose_name": "Cluster",
                "verbose_name_plural": "Clusters",
                "db_table": "cluster",
                "ordering": ["estado", "nome"],
            },
        ),
    ]
