# Generated by Django 4.2 on 2023-09-19 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("localidade", "0001_initial"),
        ("classe", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Entrada",
            fields=[
                ("id_entrada", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.DateField()),
                (
                    "peso",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "id_classe",
                    models.ForeignKey(
                        db_column="id_classe",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="classe.classe",
                    ),
                ),
                (
                    "id_localidade",
                    models.ForeignKey(
                        db_column="id_localidade",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="localidade.localidade",
                    ),
                ),
            ],
            options={
                "db_table": "entrada",
                "ordering": ["-id_entrada"],
            },
        ),
    ]
