# Generated by Django 4.2 on 2023-05-25 22:24
# Edited manually on 2023-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW v_entrada_mensal AS
            SELECT CAST(ROW_NUMBER() OVER () AS INTEGER) AS id,
                CAST(strftime('%Y',e.data) AS INTEGER) AS ano,
                CAST(strftime('%m',e.data) AS INTEGER) AS mes,
                CAST(SUM(e.peso) AS REAL) AS peso,
                l.nome AS localidade,
                c.nome AS classe
            FROM entrada e
            JOIN localidade l ON e.id_localidade = l.id_localidade
            JOIN classe c ON e.id_classe = c.id_classe
            GROUP BY ano, mes, localidade, classe;
            """,
            reverse_sql="DROP VIEW v_entrada_mensal;",
        ),

        migrations.RunSQL(
            sql="""
                CREATE VIEW v_saida_mensal AS
                SELECT CAST(ROW_NUMBER() OVER () AS INTEGER) AS id,
                    l.nome AS localidade,
                    c.nome AS classe,
                    CAST(strftime('%Y', s.data) AS INTEGER) AS ano,
                    CAST(strftime('%m', s.data) AS INTEGER) AS mes,
                    CAST(SUM(s.peso) AS REAL) AS peso,
                    CAST(SUM(s.custo) AS REAL) AS custo,
                    CAST(SUM(s.receita) AS REAL) AS receita
                FROM saida s
                JOIN localidade l ON s.id_localidade = l.id_localidade
                JOIN classe c ON s.id_classe = c.id_classe
                GROUP BY ano, mes, localidade, classe;
                """,
            reverse_sql="DROP VIEW v_saida_mensal;",
        ),

    ]
