# Generated by Django 4.2 on 2023-05-25 22:24
# Edited manually on 2023-05-25 19:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE VIEW v_entrada_mensal
            AS
            SELECT ROW_NUMBER() OVER () AS id,
                l.nome as "localidade",
                c.nome as "classe",
                strftime('%Y',e.data) as "ano",
                strftime('%m',e.data) as "mes",
                SUM(e.peso) as peso
            FROM entrada e
            JOIN localidade l
                ON e.id_localidade = l.id_localidade
            JOIN classe c
                ON e.id_classe = c.id_classe
            GROUP BY localidade, classe, ano, mes;
            """,
            reverse_sql="DROP VIEW v_entrada_mensal;",
        ),

        migrations.RunSQL(
            sql="""
                CREATE VIEW v_saida_mensal
                AS
                SELECT ROW_NUMBER() OVER () AS id,
                    l.nome as "localidade",
                    c.nome as "classe",
                    strftime('%Y',s.data) as "ano",
                    strftime('%m',s.data) as "mes",
                    SUM(s.peso) as peso,
                    SUM(s.custo) as cuso,
                    SUM(s.receita) as receita
                FROM saida s
                JOIN localidade l
                    ON s.id_localidade = l.id_localidade
                JOIN classe c
                    ON s.id_classe = c.id_classe
                GROUP BY localidade, classe, ano, mes;
                """,
            reverse_sql="DROP VIEW v_saida_mensal;",
        ),

    ]
