# Generated by Django 4.2 on 2023-09-16 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("home", "0001_create_database_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntradaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.CharField(max_length=50)),
                ("ano", models.CharField(max_length=50)),
                ("peso", models.FloatField()),
                ("classe", models.CharField(max_length=50)),
                ("localidade", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Entrada Mensal",
                "db_table": "v_entrada_mensal",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SaidaMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mes", models.CharField(max_length=50)),
                ("ano", models.CharField(max_length=50)),
                ("peso", models.DecimalField(decimal_places=2, max_digits=5)),
                ("receita", models.DecimalField(decimal_places=2, max_digits=5)),
                ("custo", models.DecimalField(decimal_places=2, max_digits=5)),
                ("classe", models.CharField(max_length=50)),
                ("localidade", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name_plural": "Saida Mensal",
                "db_table": "v_saida_mensal",
                "managed": False,
            },
        ),
    ]
