# Generated by Django 4.2 on 2023-05-13 16:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saida", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="saida",
            old_name="mtr",
            new_name="n_evidencia",
        ),
    ]
