# Generated by Django 4.2 on 2023-05-22 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("saida", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="saida",
            options={
                "ordering": ["-id_saida"],
                "verbose_name": "Saída",
                "verbose_name_plural": "Saídas",
            },
        ),
    ]
