# Generated by Django 4.2.6 on 2023-10-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fornecedor", "0001_initial"),
        ("localidade", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Combustivel",
            fields=[
                ("id_combustivel", models.AutoField(primary_key=True, serialize=False)),
                ("dt_combustivel", models.DateField()),
                ("tp_combustivel", models.CharField(max_length=20)),
                (
                    "consumo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "custo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "id_fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fornecedor.fornecedor",
                    ),
                ),
                (
                    "id_localidade",
                    models.ForeignKey(
                        db_column="id_localidade",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="localidade.localidade",
                    ),
                ),
            ],
            options={
                "verbose_name": "Combustível",
                "verbose_name_plural": "Combustíveis",
                "db_table": "combustivel",
                "ordering": ["-id_combustivel"],
            },
        ),
    ]
