# Generated by Django 4.2 on 2023-05-25 23:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Localidade",
            fields=[
                ("id_localidade", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Localidade",
                "verbose_name_plural": "Localidades",
                "db_table": "localidade",
                "ordering": ["-id_localidade"],
            },
        ),
    ]
