# Generated by Django 4.2.6 on 2023-11-01 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TipoCombustivel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Tipo de Combustível",
                "verbose_name_plural": "Tipos de Combustíveis",
                "db_table": "tp_combustivel",
                "ordering": ["-id"],
            },
        ),
    ]
