# Generated by Django 4.2.6 on 2023-10-30 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tipo_combustivel", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tipocombustivel",
            options={
                "ordering": ["-id"],
                "verbose_name": "Tipo de Combustível",
                "verbose_name_plural": "Tipos de Combustíveis",
            },
        ),
        migrations.RenameField(
            model_name="tipocombustivel",
            old_name="id_tp_combustivel",
            new_name="id",
        ),
    ]
