# Generated by Django 4.2.6 on 2023-10-31 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("fornecedor", "0001_initial"),
        ("cluster", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Eletricidade",
            fields=[
                (
                    "id_eletricidade",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("dt_eletricidade", models.DateField()),
                (
                    "consumo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "custo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "id_cluster",
                    models.ForeignKey(
                        db_column="id_cluster",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="cluster.cluster",
                    ),
                ),
                (
                    "id_fornecedor",
                    models.ForeignKey(
                        db_column="id_fornecedor",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="fornecedor.fornecedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Eletricidade",
                "verbose_name_plural": "Eletricidades",
                "db_table": "eletricidade",
                "ordering": ["-id_eletricidade"],
            },
        ),
    ]
