# Generated by Django 4.2.6 on 2023-10-31 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("eletricidade", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eletricidade",
            options={
                "ordering": ["-id"],
                "verbose_name": "Eletricidade",
                "verbose_name_plural": "Eletricidades",
            },
        ),
        migrations.RenameField(
            model_name="eletricidade",
            old_name="dt_eletricidade",
            new_name="data",
        ),
        migrations.RenameField(
            model_name="eletricidade",
            old_name="id_eletricidade",
            new_name="id",
        ),
        migrations.RemoveField(
            model_name="eletricidade",
            name="custo",
        ),
        migrations.RemoveField(
            model_name="eletricidade",
            name="id_fornecedor",
        ),
    ]
